name: Test CI

on:
  push:
    branches: [ test_ci ]
  pull_request:
    branches: [ test_ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Send Message to WeChat
        run: >-
          curl -H 'Content-type: application/json'
          --data '{"msgtype": "text","text": {"content": "hello ci"}}' 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4db2c60b-1ca8-4eb3-a67d-21226ea3fc0d'

